config/routes.rb
Rails.application.routes.draw do
  root to: "pools#index"

  resources :pools, only: [:index]
  resources :tickets, only: [:index, :new, :create]
end

app/models/pool.rb
class Pool
  def initialize(pool_attrs)
    @pool_attrs = pool_attrs
  end

  def method_missing(name)
    if pool_attrs.has_key?(name.to_s)
      return pool_attrs[name.to_s]
    end
  end

  private

  attr_reader :pool_attrs
end

app/models/pool_group.rb
class PoolGroup
  def initialize(pool_group_attrs)
    @pool_group_attrs = pool_group_attrs
  end

  def name
    pool_group_attrs["display_group_name"]
  end

  def pools
    pool_group_attrs["pools"].map{|pool| Pool.new(pool)}
  end

  private

  attr_reader :pool_group_attrs
end

app/models/ticket.rb
class Ticket
  include ActiveModel::Model
  attr_accessor :pool_id, :selections, :stake, :cost

  def initialize(ticket_attrs = {})
    @ticket_attrs = ticket_attrs
  end

  private

  attr_reader :ticket_attrs
end

app/models/ticket_group.rb
class TicketGroup
  def initialize(ticket_group_attrs)
    @ticket_group_attrs = ticket_group_attrs
  end

  def total
    ticket_group_attrs["total_items"]
  end

  def items
    ticket_group_attrs["items"].map{|ticket| Ticket.new(ticket)}
  end

  private

  attr_reader :ticket_group_attrs
end

app/controllers/application_controller.rb
require "api_connector"

class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def api
    ColossusBets::APIConnector.instance
  end

  def customer_id
    session[:customer_id] ||= SecureRandom.uuid
  end
end

app/controllers/pools_controller.rb
class PoolsController < ApplicationController
  def index
    @pool_groups = api.pools.all.map {|pool_group| PoolGroup.new(pool_group)}
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  def index
    @ticket_group = TicketGroup.new(api.tickets.all(customer_id: customer_id))
  end

  def new
    @ticket = Ticket.new
  end

  def create
    api_response = api.tickets.create(ticket_params)
    if api_response.has_key?("error") || api_response.has_key?("errors")
      flash[:error] = api_response
    else
      flash[:notice] = "Created ticket"
    end
    redirect_to tickets_path
  end

  private

  def ticket_params
    params.require(:ticket)
      .permit(:pool_id, :selections, :stake, :cost)
      .merge(customer_id: customer_id, currency: "GBP", poc: "GB")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_flashes.slim
#flash
  - flash.each do |key, value|
    .flash class="flash-#{key}" = value

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ColossusGui</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav>
  <ul>
    <li><%= link_to_unless_current "Pools", pools_path %></li>
    <li><%= link_to_unless_current "Tickets", tickets_path %></li>
  </ul>
</nav>

<%= render "flashes" %>

<%= yield %>

</body>
</html>

app/views/pools/index.slim
h1 Pools

ul
  - @pool_groups.each do |pool_group|
    li
      p = pool_group.name
      ul
        - pool_group.pools.each do |pool|
          li
            p = pool.id
            p = pool.selections
            p = pool.name
            p = pool.status

app/views/tickets/index.slim
h1 Tickets

p = "You have #{@ticket_group.total} tickets open"

= link_to "Create Ticket", new_ticket_path

ul
  - @ticket_group.items.each do |ticket|

app/views/tickets/new.slim
= form_for @ticket do |form|
  .input
    = form.label :pool_id, "Pool ID"
    = form.number_field :pool_id

  .input
    = form.label :selections, "Selections"
    = form.text_field :selections, placeholder: "Separate selections with a comma"

  .input
    = form.label :stake
    = form.text_field :stake

  .input
    = form.label :cost
    = form.text_field :cost

  = form.submit